#!/usr/bin/env bash

source "$(dirname $0)/vars"

case "$1" in
  elbdomains:get)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    hostnames_for_app "$APP"
	echo "${hostnames[@]}"
	;;

  elbdomains:set)
    verify_app_name "$2"
    shift 2
    echo "$@" > "$DOKKU_ROOT/$APP/HOSTNAME"
    redeploy_app "$APP"
    ;;

  elbdomains:redirect:get)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    hostnames_for_app "$APP"
    echo "${redirect_hostnames[@]}"
    ;;

  elbdomains:redirect:set)
    verify_app_name "$2"
    shift 2
    echo "$@" > "$DOKKU_ROOT/$APP/REDIRECT_HOSTNAME"
    redeploy_app "$APP"
    ;;

  help)
    cat && cat <<EOF
    elbdomains:get <app>                 Get domains for an app
    elbdomains:set <app> <domains...>    Set app domains
    elbdomains:redirect:get <app>                 Get redirect domains for an app
    elbdomains:redirect:set <app> <domains...>    Set redirect app domains
EOF
    ;;
esac
